### ISSUE TITLE
Conflict with PathLinker App: EdgeBetweenness column already exists 

### ISSUE THREAD

**Issue by jlaw9** [cytoscape/network-analyzer#1]
Hello,

I'm developing the [PathLinker app](http://apps.cytoscape.org/apps/pathlinker), and a user [reported a conflict](https://github.com/Murali-group/PathLinker-Cytoscape/issues/13) with the PathLinker app and the NetworkAnalyzer tool. 

The conflict is if the Cytoscape NetworkAnalyzer is run before PathLinker, PathLinker will hang with the message PathLinker is running. NetworkAnalyzer creates an edge attribute `EdgeBetweenness`, and PathLinker does not allow this attribute to exist prior to its execution. With the attribute present, I get the error message:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: column already exists with name: 'EdgeBetweenness' with type: class java.lang.Double
in table: BIOGRID-ORGANISM-Caenorhabditis_elegans-3.4.129.mitab default edge
	at org.cytoscape.model.internal.SharedTableFacade.checkIfAlreadyExists(SharedTableFacade.java:97)
	at org.cytoscape.model.internal.SharedTableFacade.createColumn(SharedTableFacade.java:116)
	at org.cytoscape.model.internal.LocalTableFacade.createColumn(LocalTableFacade.java:93)
	at org.cytoscape.model.internal.LocalTableFacade.createColumn(LocalTableFacade.java:86)
	at com.dpgil.pathlinker.path_linker.internal.PathLinkerPanel.createKSPSubgraph(PathLinkerPanel.java:931)
	at com.dpgil.pathlinker.path_linker.internal.PathLinkerPanel.runKSP(PathLinkerPanel.java:322)
	at com.dpgil.pathlinker.path_linker.internal.PathLinkerPanel.access$1(PathLinkerPanel.java:265)
	at com.dpgil.pathlinker.path_linker.internal.PathLinkerPanel$1.run(PathLinkerPanel.java:237)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
...
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

If I then delete the `EdgeBetweenness` attribute, PathLinker runs successfully. I encountered the problem with Cytoscape 3.4.0 and PathLinker 1.2.4.

PathLinker copies all of the edge columns and attributes to the new subnetwork, but before it creates an edge column in the new network, it checks to see if it already exists. It seems like the problem isn't on our end. Is this something you can fix on your end?

**Comment by jlaw9** [comment]
Also, I should mention that if I create a column named `EdgeBetweenness` in the edge table myself, PathLinker runs with no problems. However, if I try to run NetworkAnalyzer on a network with an `EdgeBetweenness` column, it quits with the error message "network contains no nodes." If I delete that column, NetworkAnalyzer runs successfully.

**Comment by bdemchak** [comment]
Hi ... You're right that conflicts can exist when two different apps use a same-named column differently. Additionally, there is also plenty of opportunity for apps to create undocumented dependencies on columns. It seems like you're running into both situations here. I'd say that this is endemic throughout the app ecosystem. In a perfect world, there could be a registry of column names and their app dependencies. We don't have this so far, but would be game for establishing something like this.

I'm not sure what kind of solution you're thinking of. Could you elaborate?? (Also, suggest we transplant this thread to cytoscape-app-dev@googlegroups.com where it can get better community involvement. OK?)

**Comment by jlaw9** [comment]
Thanks for the reply, that kind of registry seems useful!

I'm not sure what I would suggest. Maybe it's a problem with the `CyTable.getColumn(columnName)` function.

And sure, I'll move this tread to the google group.
